name: Release
on:
  release:
    types: [published]
jobs:
  trigger-circleci:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger CircleCI pipeline
        id: say_release
        uses: circleci/trigger_circleci_pipeline@v1.0
        env:
          CCI_TOKEN: $
